<?php


namespace TedbowDrupalScripts;


use Symfony\Component\Console\Style\SymfonyStyle;

class FunStyle extends SymfonyStyle
{

    /**
     * @inheritDoc
     */
    public function success($message)
    {
        parent::success($message); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function error($message)
    {
        parent::error("🔥🔥🔥{$message}🔥🔥🔥"); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function warning($message)
    {
        parent::warning($message); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function info($message)
    {
        parent::info($message); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function caution($message)
    {
        parent::caution($message); // TODO: Change the autogenerated stub
    }

}